name: Pipeline decathlon

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  checkstyle:
  
     runs-on: ubuntu-latest
    
     needs: build
 
     steps:
       - uses: actions/checkout@v2
       - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
       - name: Checkstyle with Maven
         run: mvn checkstyle:check 
   
  spotbugs:
  
   runs-on: ubuntu-latest
   
   needs: build

   steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 17
       uses: actions/setup-java@v2
       with:
         java-version: '17'
         distribution: 'adopt'
         cache: maven
     - name: Spotbugs with Maven
       run: mvn spotbugs:check 
       
  PMD:
  
   runs-on: ubuntu-latest
   
   needs: build

   steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 17
       uses: actions/setup-java@v2
       with:
         java-version: '17'
         distribution: 'adopt'
         cache: maven
     - name: PMD with Maven
       run: mvn pmd:pmd